cnvPlot: "CNV_plot_iteration_0.png"
confidencePlot: "confidence_over_time_plot_iteration_0.png"
confidenceTable: "classifier_progress_iteration_0.tsv"
predictPlot: "merged_probes_methyl_calls_model_iteration_0.png"
version: "1.0.0"
devMail: "TranslationalBioinf@prinsesmaximacentrum.nl"
refGenome: "/opt/sturgeon_gui/.resources/chm13_V2/"
model: "/opt/sturgeon_gui/.resources/Sturgeon_general_V2/model.zip"
sturgeonImage: "sturgeon:v1.0"
wrapperScript: "/opt/sturgeon/R_scripts/live_processing_fast5s_guppy_v6.5.R"
extraArgs: ""
wrapperFlagDir: "/opt/sturgeon_gui/.wrapper/"
defaultDir: "/data/"
logDir: "/opt/sturgeon_gui/.sturgeon_logs"
samplePattern: "(PM(C|A|G|L|R|O)|EXT|EGA|ENA)BM[0-9]{3}[A-Z]{3}"