cnvPlot: "CNV_plot_iteration_0.png"
confidencePlot: "confidence_over_time_plot_iteration_0.png"
confidenceTable: "classifier_progress_iteration_0.tsv"
predictPlot: "merged_probes_methyl_calls_model_iteration_0.png"
version: "1.0.0"
devMail: "TranslationalBioinf@prinsesmaximacentrum.nl"
refGenome: "/home/grid/Sturgeon/chm13_V2/"
model: "/home/grid/Sturgeon/Sturgeon_general_V2/model.zip"
sturgeonImage: "sturgeontest:v3.0"
wrapperScript: "/opt/sturgeon/R_scripts/live_processing_fast5s_guppy_v6.5.R"
extraArgs: ""
wrapperFlagDir: "/home/grid/wrapper/"
defaultDir: "/data/"